// Traductions du site : chaque ligne = [français, anglais, allemand, espagnol, italien].
// Le français est le texte exact des pages de site/ (espaces normalisés). Après une modification d'un texte français,
// mettre la ligne à jour ici, puis lancer : node traduire.cjs
module.exports = [
  // --- Commun : en-tête, menu, pied de page ---
  ["Aller au contenu", "Skip to content", "Zum Inhalt springen", "Ir al contenido", "Vai al contenuto"],
  ["Sally Home Connect", "Sally Home Connect", "Sally Home Connect", "Sally Home Connect", "Sally Home Connect"],
  ["Fonctionnalités", "Features", "Funktionen", "Funciones", "Funzionalità"],
  ["Compatibilité", "Compatibility", "Kompatibilität", "Compatibilidad", "Compatibilità"],
  ["Contact", "Contact", "Kontakt", "Contacto", "Contatti"],
  ["Obtenir Sally", "Get Sally", "Sally holen", "Obtener Sally", "Ottieni Sally"],
  ["Ouvrir le menu", "Open the menu", "Menü öffnen", "Abrir el menú", "Apri il menu"],
  ["Menu principal", "Main menu", "Hauptmenü", "Menú principal", "Menu principale"],
  ["© 2026 Sally Home Connect. Ta maison connectée, sans travaux, et tes données restent chez toi.",
    "© 2026 Sally Home Connect. Your connected home, no renovation work, and your data stays at home.",
    "© 2026 Sally Home Connect. Dein vernetztes Zuhause, ohne Umbau, und deine Daten bleiben bei dir.",
    "© 2026 Sally Home Connect. Tu casa conectada, sin obras, y tus datos se quedan en casa.",
    "© 2026 Sally Home Connect. La tua casa connessa, senza lavori, e i tuoi dati restano a casa tua."],
  ["Mentions légales", "Legal notice", "Impressum", "Aviso legal", "Note legali"],
  ["Devenir testeur", "Become a tester", "Tester werden", "Ser probador", "Diventa tester"],
  ["sallyhomeconnect@gmail.com", "sallyhomeconnect@gmail.com", "sallyhomeconnect@gmail.com", "sallyhomeconnect@gmail.com", "sallyhomeconnect@gmail.com"],
  ["Zigbee", "Zigbee", "Zigbee", "Zigbee", "Zigbee"],
  ["EnOcean", "EnOcean", "EnOcean", "EnOcean", "EnOcean"],
  ["(s'ouvre dans un nouvel onglet)", "(opens in a new tab)", "(öffnet in einem neuen Tab)", "(se abre en una pestaña nueva)", "(si apre in una nuova scheda)"],
  ["Les fonctions, une par une", "The features, one by one", "Die Funktionen im Einzelnen", "Las funciones, una a una", "Le funzionalità, una per una"],
  ["Le matériel nécessaire", "Required hardware", "Benötigte Hardware", "El material necesario", "L'hardware necessario"],
  ["Les façons de nous écrire", "Ways to write to us", "So erreichst du uns", "Formas de escribirnos", "Come scriverci"],
  ["noindex", "noindex", "noindex", "noindex", "noindex"],

  // --- Accueil ---
  ["Sally Home Connect : la maison connectée 100 % locale, sans cloud",
    "Sally Home Connect: the 100% local smart home, no cloud",
    "Sally Home Connect: das 100 % lokale Smart Home, ohne Cloud",
    "Sally Home Connect: la casa conectada 100 % local, sin nube",
    "Sally Home Connect: la casa connessa 100% locale, senza cloud"],
  ["Sally pilote tes lumières, tes volets et ton chauffage depuis ton téléphone. Tout reste chez toi : pas de cloud, pas de compte, pas d'abonnement.",
    "Sally controls your lights, shutters and heating from your phone. Everything stays at home: no cloud, no account, no subscription.",
    "Sally steuert Licht, Rollläden und Heizung über dein Handy. Alles bleibt bei dir: keine Cloud, kein Konto, kein Abo.",
    "Sally controla tus luces, persianas y calefacción desde el móvil. Todo se queda en casa: sin nube, sin cuenta, sin suscripción.",
    "Sally comanda luci, tapparelle e riscaldamento dal telefono. Tutto resta a casa tua: niente cloud, niente account, niente abbonamento."],
  ["Maison connectée 100 % locale", "100% local smart home", "100 % lokales Smart Home", "Casa conectada 100 % local", "Casa connessa 100% locale"],
  ["Ta maison connectée,", "Your connected home,", "Dein vernetztes Zuhause,", "Tu casa conectada,", "La tua casa connessa,"],
  ["sans travaux", "no renovation work", "ohne Umbau", "sin obras", "senza lavori"],
  [", et tes données restent chez toi.", ", and your data stays at home.", ", und deine Daten bleiben bei dir.", ", y tus datos se quedan en casa.", ", e i tuoi dati restano a casa tua."],
  ["Sally pilote tes lumières, tes volets et ton chauffage depuis ton téléphone ou ton ordinateur. Elle tourne chez toi, sans cloud, sans compte et sans abonnement.",
    "Sally controls your lights, shutters and heating from your phone or computer. It runs in your home, with no cloud, no account and no subscription.",
    "Sally steuert Licht, Rollläden und Heizung über Handy oder Computer. Sie läuft bei dir zu Hause, ohne Cloud, ohne Konto und ohne Abo.",
    "Sally controla tus luces, persianas y calefacción desde el móvil o el ordenador. Funciona en tu casa, sin nube, sin cuenta y sin suscripción.",
    "Sally comanda luci, tapparelle e riscaldamento dal telefono o dal computer. Funziona a casa tua, senza cloud, senza account e senza abbonamento."],
  ["Découvrir ce que fait Sally", "See what Sally does", "Entdecke, was Sally kann", "Descubre lo que hace Sally", "Scopri cosa fa Sally"],
  ["Essayer gratuitement", "Try it for free", "Kostenlos testen", "Probar gratis", "Prova gratis"],
  ["Aucune donnée ne sort de chez toi", "No data leaves your home", "Keine Daten verlassen dein Zuhause", "Ningún dato sale de tu casa", "Nessun dato esce da casa tua"],
  ["Fonctionne sans Internet", "Works without Internet", "Funktioniert ohne Internet", "Funciona sin Internet", "Funziona senza Internet"],
  ["Sans abonnement", "No subscription", "Ohne Abo", "Sin suscripción", "Senza abbonamento"],
  ["Simple comme une application, privée comme ta maison", "As simple as an app, as private as your home", "Einfach wie eine App, privat wie dein Zuhause", "Sencilla como una app, privada como tu casa", "Semplice come un'app, riservata come la tua casa"],
  ["La plupart des maisons connectées passent par les serveurs d'une marque. Sally fait le contraire : tout se passe entre ton téléphone et l'ordinateur qui est chez toi.",
    "Most smart homes go through a brand's servers. Sally does the opposite: everything happens between your phone and the computer in your home.",
    "Die meisten Smart Homes laufen über die Server eines Herstellers. Sally macht es umgekehrt: Alles passiert zwischen deinem Handy und dem Computer bei dir zu Hause.",
    "La mayoría de las casas conectadas pasan por los servidores de una marca. Sally hace lo contrario: todo ocurre entre tu móvil y el ordenador que tienes en casa.",
    "La maggior parte delle case connesse passa dai server di un marchio. Sally fa il contrario: tutto avviene tra il tuo telefono e il computer che hai in casa."],
  ["Tes données restent chez toi", "Your data stays at home", "Deine Daten bleiben bei dir", "Tus datos se quedan en casa", "I tuoi dati restano a casa tua"],
  ["Sally ne crée pas de compte et n'envoie rien sur Internet. Ce qui se passe dans ta maison ne regarde que toi.",
    "Sally creates no account and sends nothing over the Internet. What happens in your home is nobody's business but yours.",
    "Sally legt kein Konto an und schickt nichts ins Internet. Was in deinem Zuhause passiert, geht nur dich etwas an.",
    "Sally no crea ninguna cuenta y no envía nada a Internet. Lo que pasa en tu casa solo te concierne a ti.",
    "Sally non crea nessun account e non invia nulla su Internet. Quello che succede in casa tua riguarda solo te."],
  ["Aucun réglage technique", "No technical setup", "Keine technischen Einstellungen", "Sin ajustes técnicos", "Nessuna impostazione tecnica"],
  ["Sally te guide pas à pas pour ajouter une ampoule, une prise, un volet ou un radiateur. Tu lui réponds à la voix ou d'un toucher, elle fait le reste.",
    "Sally guides you step by step to add a bulb, a plug, a shutter or a radiator. You answer by voice or with a tap, and it does the rest.",
    "Sally führt dich Schritt für Schritt, um eine Lampe, eine Steckdose, einen Rollladen oder einen Heizkörper hinzuzufügen. Du antwortest per Sprache oder Fingertipp, Sally erledigt den Rest.",
    "Sally te guía paso a paso para añadir una bombilla, un enchufe, una persiana o un radiador. Le respondes con la voz o con un toque, y ella hace el resto.",
    "Sally ti guida passo dopo passo per aggiungere una lampadina, una presa, una tapparella o un termosifone. Rispondi a voce o con un tocco, al resto pensa lei."],
  ["Pas de frais mensuels, pas de service qui ferme du jour au lendemain. Si Internet tombe en panne, ta maison continue de fonctionner.",
    "No monthly fees, no service that shuts down overnight. If the Internet goes down, your home keeps working.",
    "Keine monatlichen Kosten, kein Dienst, der von heute auf morgen schließt. Fällt das Internet aus, funktioniert dein Zuhause weiter.",
    "Sin cuotas mensuales, sin servicios que cierran de un día para otro. Si se cae Internet, tu casa sigue funcionando.",
    "Nessun costo mensile, nessun servizio che chiude da un giorno all'altro. Se Internet si interrompe, la tua casa continua a funzionare."],
  ["Une maison qui agit toute seule", "A home that acts on its own", "Ein Zuhause, das von selbst handelt", "Una casa que actúa sola", "Una casa che fa da sola"],
  ["Tu dis à Sally quoi faire, et quand. Elle s'en occupe ensuite sans que tu y penses.",
    "You tell Sally what to do, and when. Then it takes care of it without you having to think about it.",
    "Du sagst Sally, was sie wann tun soll. Danach kümmert sie sich darum, ohne dass du daran denken musst.",
    "Le dices a Sally qué hacer y cuándo. Después ella se encarga, sin que tengas que pensar en ello.",
    "Dici a Sally cosa fare e quando. Poi se ne occupa lei, senza che tu ci debba pensare."],
  ["Au coucher du soleil", "At sunset", "Bei Sonnenuntergang", "Al atardecer", "Al tramonto"],
  [", les volets se ferment.", ", the shutters close.", " schließen sich die Rollläden.", ", las persianas se cierran.", ", le tapparelle si chiudono."],
  ["Quand la porte s'ouvre la nuit", "When the door opens at night", "Wenn sich nachts die Tür öffnet", "Cuando la puerta se abre de noche", "Quando la porta si apre di notte"],
  [", la lumière de l'entrée s'allume.", ", the hall light comes on.", ", geht das Licht im Flur an.", ", se enciende la luz de la entrada.", ", si accende la luce dell'ingresso."],
  ["En cas de fuite d'eau", "If there is a water leak", "Bei einem Wasserleck", "Si hay una fuga de agua", "In caso di perdita d'acqua"],
  [", Sally te prévient et coupe la prise.", ", Sally warns you and switches off the plug.", " warnt dich Sally und schaltet die Steckdose ab.", ", Sally te avisa y corta el enchufe.", ", Sally ti avvisa e spegne la presa."],
  ["Le matin", "In the morning", "Am Morgen", "Por la mañana", "Al mattino"],
  [", le chauffage est déjà en mode confort.", ", the heating is already in comfort mode.", " ist die Heizung schon im Komfortmodus.", ", la calefacción ya está en modo confort.", ", il riscaldamento è già in modalità comfort."],
  ["Ta consommation, en clair", "Your energy use, made clear", "Dein Verbrauch, ganz klar", "Tu consumo, con claridad", "I tuoi consumi, in chiaro"],
  ["Sally additionne ce que consomment tes radiateurs et tes prises, et te donne le coût en euros avec ton prix de l'électricité, heures creuses comprises.",
    "Sally adds up what your radiators and plugs use, and gives you the cost in euros at your electricity price, off-peak hours included.",
    "Sally zählt zusammen, was deine Heizkörper und Steckdosen verbrauchen, und zeigt dir die Kosten in Euro mit deinem Strompreis, Nebenzeiten inklusive.",
    "Sally suma lo que consumen tus radiadores y enchufes, y te da el coste en euros según tu precio de la electricidad, horas valle incluidas.",
    "Sally somma quello che consumano termosifoni e prese, e ti dà il costo in euro con il tuo prezzo dell'elettricità, fasce orarie ridotte comprese."],
  ["La puissance utilisée en ce moment.", "The power being used right now.", "Die gerade genutzte Leistung.", "La potencia que se usa en este momento.", "La potenza usata in questo momento."],
  ["Le total du jour, de la semaine et du mois.", "The total for the day, the week and the month.", "Die Summe des Tages, der Woche und des Monats.", "El total del día, de la semana y del mes.", "Il totale del giorno, della settimana e del mese."],
  ["Le détail appareil par appareil.", "The breakdown device by device.", "Die Aufschlüsselung Gerät für Gerät.", "El detalle aparato por aparato.", "Il dettaglio dispositivo per dispositivo."],
  ["Comment ça marche", "How it works", "So funktioniert's", "Cómo funciona", "Come funziona"],
  ["Sally est un logiciel. Tu l'installes sur un ordinateur qui reste allumé chez toi, et tu la pilotes depuis n'importe quel écran de la maison.",
    "Sally is software. You install it on a computer that stays on in your home, and you control it from any screen in the house.",
    "Sally ist eine Software. Du installierst sie auf einem Computer, der bei dir zu Hause eingeschaltet bleibt, und steuerst sie von jedem Bildschirm im Haus.",
    "Sally es un programa. Lo instalas en un ordenador que se queda encendido en casa y lo controlas desde cualquier pantalla de la casa.",
    "Sally è un software. Lo installi su un computer che resta acceso a casa tua e lo comandi da qualsiasi schermo della casa."],
  ["Installe Sally", "Install Sally", "Installiere Sally", "Instala Sally", "Installa Sally"],
  ["Essaie-la gratuitement sur un ordinateur Windows. Pour vivre avec, la version finale tournera sur un Raspberry Pi, un petit boîtier qui reste allumé jour et nuit.",
    "Try it for free on a Windows computer. To live with it, the final version will run on a Raspberry Pi, a small box that stays on day and night.",
    "Teste sie kostenlos auf einem Windows-Computer. Für den Alltag läuft die finale Version auf einem Raspberry Pi, einem kleinen Gerät, das Tag und Nacht eingeschaltet bleibt.",
    "Pruébala gratis en un ordenador con Windows. Para el día a día, la versión final funcionará en una Raspberry Pi, una cajita que se queda encendida día y noche.",
    "Provala gratis su un computer Windows. Per l'uso quotidiano, la versione finale girerà su un Raspberry Pi, una piccola scatola che resta accesa giorno e notte."],
  ["Branche une clé USB", "Plug in a USB stick", "Steck einen USB-Stick ein", "Conecta una llave USB", "Collega una chiavetta USB"],
  ["Une clé Zigbee, une clé EnOcean, ou les deux. C'est elle qui parle à tes appareils, par radio.",
    "A Zigbee stick, an EnOcean stick, or both. It talks to your devices by radio.",
    "Ein Zigbee-Stick, ein EnOcean-Stick oder beide. Er spricht per Funk mit deinen Geräten.",
    "Una llave Zigbee, una llave EnOcean, o las dos. Es la que habla con tus aparatos, por radio.",
    "Una chiavetta Zigbee, una EnOcean, o entrambe. È lei che parla con i tuoi dispositivi, via radio."],
  ["Ajoute tes appareils", "Add your devices", "Füge deine Geräte hinzu", "Añade tus aparatos", "Aggiungi i tuoi dispositivi"],
  ["Sally les reconnaît et te guide, à la voix si tu veux. Tu ouvres ensuite l'application sur ton téléphone, à l'adresse sally.local.",
    "Sally recognises them and guides you, by voice if you like. Then you open the app on your phone, at the address sally.local.",
    "Sally erkennt sie und führt dich, auf Wunsch per Sprache. Danach öffnest du die App auf deinem Handy unter der Adresse sally.local.",
    "Sally los reconoce y te guía, con la voz si quieres. Después abres la aplicación en tu móvil, en la dirección sally.local.",
    "Sally li riconosce e ti guida, anche a voce se vuoi. Poi apri l'app sul telefono, all'indirizzo sally.local."],
  ["Essaie Sally gratuitement", "Try Sally for free", "Teste Sally kostenlos", "Prueba Sally gratis", "Prova Sally gratis"],
  ["La bêta pour Windows est disponible : 30 jours d'essai complet, sans compte et sans carte bancaire. Une démonstration est incluse pour tout découvrir sans matériel.",
    "The Windows beta is available: a full 30-day trial, no account and no credit card. A demo is included so you can explore everything without any hardware.",
    "Die Beta für Windows ist verfügbar: 30 Tage voller Testzeitraum, ohne Konto und ohne Kreditkarte. Eine Demo ist dabei, um alles ohne Hardware zu entdecken.",
    "La beta para Windows está disponible: 30 días de prueba completa, sin cuenta y sin tarjeta bancaria. Incluye una demostración para descubrirlo todo sin material.",
    "La beta per Windows è disponibile: 30 giorni di prova completa, senza account e senza carta di credito. È inclusa una demo per scoprire tutto senza hardware."],
  ["Télécharger la bêta", "Download the beta", "Beta herunterladen", "Descargar la beta", "Scarica la beta"],
  ["Le tableau de bord de Sally sur un ordinateur : lumières, volets, chauffage et ambiances, pièce par pièce.",
    "Sally's dashboard on a computer: lights, shutters, heating and scenes, room by room.",
    "Sallys Übersicht auf einem Computer: Licht, Rollläden, Heizung und Szenen, Raum für Raum.",
    "El panel de Sally en un ordenador: luces, persianas, calefacción y ambientes, habitación por habitación.",
    "La dashboard di Sally su un computer: luci, tapparelle, riscaldamento e scenari, stanza per stanza."],
  ["Le même tableau de bord sur un téléphone.", "The same dashboard on a phone.", "Dieselbe Übersicht auf einem Handy.", "El mismo panel en un móvil.", "La stessa dashboard su un telefono."],
  ["L'écran Routines de Sally : volets fermés au coucher du soleil, lumière de l'entrée à l'arrivée, alerte en cas de fuite d'eau.",
    "Sally's Routines screen: shutters closed at sunset, hall light on arrival, alert in case of a water leak.",
    "Sallys Routinen-Bildschirm: Rollläden zu bei Sonnenuntergang, Flurlicht bei der Ankunft, Alarm bei Wasserleck.",
    "La pantalla Rutinas de Sally: persianas cerradas al atardecer, luz de la entrada al llegar, alerta en caso de fuga de agua.",
    "La schermata Routine di Sally: tapparelle chiuse al tramonto, luce dell'ingresso all'arrivo, allarme in caso di perdita d'acqua."],
  ["L'écran Énergie de Sally : consommation du moment, du jour, de la semaine et par appareil, avec le coût en euros.",
    "Sally's Energy screen: current, daily, weekly and per-device consumption, with the cost in euros.",
    "Sallys Energie-Bildschirm: aktueller Verbrauch, pro Tag, pro Woche und pro Gerät, mit den Kosten in Euro.",
    "La pantalla Energía de Sally: consumo del momento, del día, de la semana y por aparato, con el coste en euros.",
    "La schermata Energia di Sally: consumo del momento, del giorno, della settimana e per dispositivo, con il costo in euro."],

  // --- Fonctionnalités ---
  ["Fonctionnalités de Sally Home Connect : lumières, volets, chauffage, routines, énergie",
    "Sally Home Connect features: lights, shutters, heating, routines, energy",
    "Funktionen von Sally Home Connect: Licht, Rollläden, Heizung, Routinen, Energie",
    "Funciones de Sally Home Connect: luces, persianas, calefacción, rutinas, energía",
    "Funzionalità di Sally Home Connect: luci, tapparelle, riscaldamento, routine, energia"],
  ["Tout ce que fait Sally", "Everything Sally does", "Alles, was Sally kann", "Todo lo que hace Sally", "Tutto quello che fa Sally"],
  ["Une seule application pour toute la maison, sur téléphone, tablette et ordinateur. Chaque fonction marche sans Internet.",
    "One app for the whole house, on phone, tablet and computer. Every feature works without the Internet.",
    "Eine einzige App für das ganze Haus, auf Handy, Tablet und Computer. Jede Funktion klappt ohne Internet.",
    "Una sola aplicación para toda la casa, en móvil, tableta y ordenador. Cada función va sin Internet.",
    "Un'unica app per tutta la casa, su telefono, tablet e computer. Ogni funzione va senza Internet."],
  ["Lumières et prises", "Lights and plugs", "Licht und Steckdosen", "Luces y enchufes", "Luci e prese"],
  ["Allume, éteins et règle l'intensité d'un geste. Une pastille éteint ou allume toute la maison d'un coup.",
    "Switch on, switch off and dim with a single gesture. One button turns the whole house on or off at once.",
    "Ein, aus und dimmen mit einer Geste. Ein Knopf schaltet das ganze Haus auf einmal ein oder aus.",
    "Enciende, apaga y regula la intensidad con un gesto. Un botón enciende o apaga toda la casa de golpe.",
    "Accendi, spegni e regola l'intensità con un gesto. Un pulsante accende o spegne tutta la casa in un colpo."],
  ["Volets roulants", "Roller shutters", "Rollläden", "Persianas", "Tapparelle"],
  ["Monte, descends ou arrête chaque volet, ou tous ensemble. Sally peut les fermer seule au coucher du soleil.",
    "Raise, lower or stop each shutter, or all of them together. Sally can close them by itself at sunset.",
    "Hoch, runter oder Stopp für jeden Rollladen oder alle zusammen. Sally kann sie bei Sonnenuntergang selbst schließen.",
    "Sube, baja o para cada persiana, o todas a la vez. Sally puede cerrarlas sola al atardecer.",
    "Alza, abbassa o ferma ogni tapparella, o tutte insieme. Sally può chiuderle da sola al tramonto."],
  ["Chauffage", "Heating", "Heizung", "Calefacción", "Riscaldamento"],
  ["Radiateurs électriques à fil pilote : confort, éco, hors gel ou arrêt, pièce par pièce, avec la puissance consommée.",
    "Electric radiators with pilot wire: comfort, eco, frost protection or off, room by room, with the power used.",
    "Elektroheizkörper mit Steuerleitung (fil pilote): Komfort, Eco, Frostschutz oder Aus, Raum für Raum, mit der verbrauchten Leistung.",
    "Radiadores eléctricos con hilo piloto: confort, eco, antihielo o apagado, habitación por habitación, con la potencia consumida.",
    "Termosifoni elettrici a filo pilota: comfort, eco, antigelo o spento, stanza per stanza, con la potenza consumata."],
  ["Chauffage programmé", "Scheduled heating", "Zeitgesteuerte Heizung", "Calefacción programada", "Riscaldamento programmato"],
  ["Choisis les heures de confort pour chaque jour de la semaine. Le reste du temps, Sally baisse le chauffage toute seule.",
    "Choose the comfort hours for each day of the week. The rest of the time, Sally turns the heating down by itself.",
    "Wähle die Komfortzeiten für jeden Wochentag. Den Rest der Zeit senkt Sally die Heizung von selbst.",
    "Elige las horas de confort para cada día de la semana. El resto del tiempo, Sally baja la calefacción sola.",
    "Scegli le ore di comfort per ogni giorno della settimana. Il resto del tempo, Sally abbassa il riscaldamento da sola."],
  ["Routines", "Routines", "Routinen", "Rutinas", "Routine"],
  ["« Quand… si… alors… » : à une heure précise, au lever ou au coucher du soleil, ou quand un capteur réagit.",
    "“When… if… then…”: at a set time, at sunrise or sunset, or when a sensor reacts.",
    "„Wenn… falls… dann…“: zu einer festen Uhrzeit, bei Sonnenaufgang oder -untergang oder wenn ein Sensor reagiert.",
    "«Cuando… si… entonces…»: a una hora concreta, al amanecer o al atardecer, o cuando un sensor reacciona.",
    "«Quando… se… allora…»: a un'ora precisa, all'alba o al tramonto, o quando un sensore reagisce."],
  ["Ambiances", "Scenes", "Szenen", "Ambientes", "Scenari"],
  ["« Je pars », « Soirée film », « Bonne nuit », « Réveil » : plusieurs appareils réglés d'un seul bouton. Tu peux créer les tiennes.",
    "“I'm leaving”, “Movie night”, “Good night”, “Wake up”: several devices set with a single button. You can create your own.",
    "„Ich gehe“, „Filmabend“, „Gute Nacht“, „Aufwachen“: mehrere Geräte mit einem einzigen Knopf eingestellt. Du kannst eigene anlegen.",
    "«Me voy», «Noche de cine», «Buenas noches», «Despertar»: varios aparatos ajustados con un solo botón. Puedes crear los tuyos.",
    "«Esco», «Serata film», «Buonanotte», «Sveglia»: più dispositivi regolati con un solo pulsante. Puoi crearne di tuoi."],
  ["Énergie et coût", "Energy and cost", "Energie und Kosten", "Energía y coste", "Energia e costi"],
  ["La consommation du moment, du jour, de la semaine et du mois, appareil par appareil, avec le coût en euros.",
    "Consumption right now, for the day, the week and the month, device by device, with the cost in euros.",
    "Der Verbrauch im Moment, pro Tag, pro Woche und pro Monat, Gerät für Gerät, mit den Kosten in Euro.",
    "El consumo del momento, del día, de la semana y del mes, aparato por aparato, con el coste en euros.",
    "Il consumo del momento, del giorno, della settimana e del mese, dispositivo per dispositivo, con il costo in euro."],
  ["Mode de la maison", "Home mode", "Hausmodus", "Modo de la casa", "Modalità della casa"],
  ["Présent, absent, nuit ou vacances. En vacances, Sally peut allumer quelques lampes le soir pour que la maison semble habitée.",
    "Home, away, night or holiday. On holiday, Sally can switch on a few lamps in the evening so the house looks lived in.",
    "Zu Hause, abwesend, Nacht oder Urlaub. Im Urlaub kann Sally abends ein paar Lampen einschalten, damit das Haus bewohnt wirkt.",
    "En casa, fuera, noche o vacaciones. En vacaciones, Sally puede encender algunas lámparas por la noche para que la casa parezca habitada.",
    "Presente, assente, notte o vacanze. In vacanza, Sally può accendere qualche lampada la sera perché la casa sembri abitata."],
  ["Capteurs", "Sensors", "Sensoren", "Sensores", "Sensori"],
  ["Température, mouvement, ouverture de porte, fuite d'eau, fumée : Sally affiche leur état et s'en sert dans les routines.",
    "Temperature, motion, door opening, water leak, smoke: Sally shows their status and uses them in routines.",
    "Temperatur, Bewegung, Türöffnung, Wasserleck, Rauch: Sally zeigt ihren Zustand an und nutzt sie in Routinen.",
    "Temperatura, movimiento, apertura de puerta, fuga de agua, humo: Sally muestra su estado y los usa en las rutinas.",
    "Temperatura, movimento, apertura della porta, perdita d'acqua, fumo: Sally ne mostra lo stato e li usa nelle routine."],
  ["Alertes et journal", "Alerts and log", "Alarme und Protokoll", "Alertas y registro", "Avvisi e registro"],
  ["Fuite, fumée, pile faible, appareil qui ne répond plus : Sally le signale et garde la trace de ce qui s'est passé.",
    "Leak, smoke, low battery, a device that stops responding: Sally reports it and keeps a record of what happened.",
    "Leck, Rauch, schwache Batterie, ein Gerät, das nicht mehr antwortet: Sally meldet es und hält fest, was passiert ist.",
    "Fuga, humo, pila baja, un aparato que no responde: Sally lo avisa y guarda constancia de lo ocurrido.",
    "Perdita, fumo, batteria scarica, un dispositivo che non risponde più: Sally lo segnala e tiene traccia di quanto successo."],
  ["Sauvegarde", "Backup", "Sicherung", "Copia de seguridad", "Backup"],
  ["Toute ta maison tient dans un seul fichier. Il permet de tout réinstaller sans refaire les réglages.",
    "Your whole home fits in a single file. It lets you reinstall everything without redoing the settings.",
    "Dein ganzes Zuhause passt in eine einzige Datei. Damit installierst du alles neu, ohne die Einstellungen zu wiederholen.",
    "Toda tu casa cabe en un solo archivo. Permite reinstalarlo todo sin rehacer los ajustes.",
    "Tutta la tua casa sta in un solo file. Permette di reinstallare tutto senza rifare le impostazioni."],
  ["À ton goût", "Your way", "Nach deinem Geschmack", "A tu gusto", "A modo tuo"],
  ["Cinq thèmes de couleurs, quatre tailles d'affichage et cinq langues : français, anglais, espagnol, italien et allemand.",
    "Five colour themes, four display sizes and five languages: French, English, Spanish, Italian and German.",
    "Fünf Farbthemen, vier Anzeigegrößen und fünf Sprachen: Französisch, Englisch, Spanisch, Italienisch und Deutsch.",
    "Cinco temas de color, cuatro tamaños de pantalla y cinco idiomas: francés, inglés, español, italiano y alemán.",
    "Cinque temi di colore, quattro dimensioni di visualizzazione e cinque lingue: francese, inglese, spagnolo, italiano e tedesco."],
  ["Commande vocale", "Voice control", "Sprachsteuerung", "Control por voz", "Comando vocale"],
  ["« Allume la lumière du salon », « ferme les volets », « soirée film » : Sally comprend ta voix sans Internet. Rien de ce que tu dis ne quitte la maison. Quand tu ajoutes un appareil, elle te demande même à voix haute dans quelle pièce le mettre. En français pour l'instant.",
    "“Turn on the living room light”, “close the shutters”, “movie night”: Sally understands your voice without the Internet. Nothing you say leaves the house. When you add a device, it even asks you out loud which room to put it in. In French only for now.",
    "„Mach das Licht im Wohnzimmer an“, „schließ die Rollläden“, „Filmabend“: Sally versteht deine Stimme ohne Internet. Nichts, was du sagst, verlässt das Haus. Wenn du ein Gerät hinzufügst, fragt sie dich sogar laut, in welchen Raum es kommt. Vorerst nur auf Französisch.",
    "«Enciende la luz del salón», «cierra las persianas», «noche de cine»: Sally entiende tu voz sin Internet. Nada de lo que dices sale de casa. Cuando añades un aparato, incluso te pregunta en voz alta en qué habitación ponerlo. Por ahora, solo en francés.",
    "«Accendi la luce del soggiorno», «chiudi le tapparelle», «serata film»: Sally capisce la tua voce senza Internet. Niente di quello che dici esce di casa. Quando aggiungi un dispositivo, ti chiede persino ad alta voce in quale stanza metterlo. Per ora solo in francese."],
  ["Interrupteurs reliés", "Linked switches", "Verknüpfte Schalter", "Interruptores vinculados", "Interruttori collegati"],
  ["Un interrupteur sans pile peut commander un volet, une lampe ou une prise. Sally te demande lequel, tu appuies sur ses touches, c'est relié.",
    "A battery-free switch can control a shutter, a lamp or a plug. Sally asks you which one, you press its buttons, and it's linked.",
    "Ein Schalter ohne Batterie kann einen Rollladen, eine Lampe oder eine Steckdose steuern. Sally fragt dich, welches Gerät, du drückst seine Tasten, fertig verknüpft.",
    "Un interruptor sin pila puede controlar una persiana, una lámpara o un enchufe. Sally te pregunta cuál, pulsas sus teclas y queda vinculado.",
    "Un interruttore senza batteria può comandare una tapparella, una lampada o una presa. Sally ti chiede quale, premi i suoi tasti ed è collegato."],
  ["Un guide intégré", "A built-in guide", "Eine eingebaute Anleitung", "Una guía integrada", "Una guida integrata"],
  ["L'onglet Aide de l'application explique tout, sujet par sujet : ajouter un appareil, parler à Sally, créer une routine, sauvegarder ta maison.",
    "The app's Help tab explains everything, topic by topic: adding a device, talking to Sally, creating a routine, backing up your home.",
    "Der Hilfe-Tab der App erklärt alles, Thema für Thema: ein Gerät hinzufügen, mit Sally sprechen, eine Routine anlegen, dein Zuhause sichern.",
    "La pestaña Ayuda de la aplicación lo explica todo, tema por tema: añadir un aparato, hablar con Sally, crear una rutina, guardar tu casa.",
    "La scheda Aiuto dell'app spiega tutto, argomento per argomento: aggiungere un dispositivo, parlare con Sally, creare una routine, salvare la tua casa."],
  ["Pièce par pièce", "Room by room", "Raum für Raum", "Habitación por habitación", "Stanza per stanza"],
  ["Chaque pièce a son image et ses appareils. L'image s'éclaire quand une lampe y est allumée, et s'assombrit quand tout est éteint : tu vois l'état de la maison d'un coup d'œil.",
    "Each room has its own picture and devices. The picture lights up when a lamp is on there, and darkens when everything is off: you see the state of the house at a glance.",
    "Jeder Raum hat sein Bild und seine Geräte. Das Bild wird hell, wenn dort eine Lampe brennt, und dunkel, wenn alles aus ist: So siehst du den Zustand des Hauses auf einen Blick.",
    "Cada habitación tiene su imagen y sus aparatos. La imagen se ilumina cuando hay una lámpara encendida y se oscurece cuando todo está apagado: ves el estado de la casa de un vistazo.",
    "Ogni stanza ha la sua immagine e i suoi dispositivi. L'immagine si illumina quando una lampada è accesa e si scurisce quando tutto è spento: vedi lo stato della casa a colpo d'occhio."],
  ["Un toucher sur une tuile allume ou éteint.", "One tap on a tile switches on or off.", "Ein Fingertipp auf eine Kachel schaltet ein oder aus.", "Un toque en una casilla enciende o apaga.", "Un tocco su un riquadro accende o spegne."],
  ["Ce qui est allumé est toujours en ambre.", "Whatever is on is always shown in amber.", "Was eingeschaltet ist, leuchtet immer bernsteinfarben.", "Lo que está encendido siempre aparece en ámbar.", "Ciò che è acceso è sempre color ambra."],
  ["Si un appareil ne répond pas, Sally te le dit en quelques secondes.", "If a device doesn't respond, Sally tells you within seconds.", "Wenn ein Gerät nicht antwortet, sagt Sally es dir in wenigen Sekunden.", "Si un aparato no responde, Sally te lo dice en pocos segundos.", "Se un dispositivo non risponde, Sally te lo dice in pochi secondi."],
  ["Et Internet ?", "What about the Internet?", "Und das Internet?", "¿Y el Internet?", "E Internet?"],
  ["Sally n'en a pas besoin. Un seul réglage, éteint au départ, l'autorise à consulter une information publique.",
    "Sally doesn't need it. A single setting, off by default, allows it to look up one piece of public information.",
    "Sally braucht es nicht. Eine einzige Einstellung, ab Werk ausgeschaltet, erlaubt ihr, eine öffentliche Information abzurufen.",
    "Sally no lo necesita. Un único ajuste, apagado de entrada, le permite consultar una información pública.",
    "Sally non ne ha bisogno. Un'unica impostazione, spenta all'inizio, le permette di consultare un'informazione pubblica."],
  ["Éteint au départ", "Off by default", "Ab Werk aus", "Apagado de entrada", "Spento all'inizio"],
  ["Tant que tu ne l'allumes pas, Sally ne consulte jamais Internet. Tout le reste fonctionne exactement pareil.",
    "As long as you don't turn it on, Sally never accesses the Internet. Everything else works exactly the same.",
    "Solange du sie nicht einschaltest, greift Sally nie auf das Internet zu. Alles andere funktioniert genau gleich.",
    "Mientras no lo actives, Sally nunca consulta Internet. Todo lo demás funciona exactamente igual.",
    "Finché non la accendi, Sally non consulta mai Internet. Tutto il resto funziona esattamente allo stesso modo."],
  ["La météo, si tu le veux", "The weather, if you want it", "Das Wetter, wenn du willst", "El tiempo, si lo quieres", "Il meteo, se lo vuoi"],
  ["Une fois autorisée, Sally affiche la météo de ta ville. Seule la position de la ville choisie est envoyée, rien de ta maison.",
    "Once allowed, Sally shows the weather for your town. Only the location of the chosen town is sent, nothing about your home.",
    "Sobald erlaubt, zeigt Sally das Wetter deiner Stadt an. Gesendet wird nur die Lage der gewählten Stadt, nichts aus deinem Zuhause.",
    "Una vez autorizada, Sally muestra el tiempo de tu ciudad. Solo se envía la ubicación de la ciudad elegida, nada de tu casa.",
    "Una volta autorizzata, Sally mostra il meteo della tua città. Viene inviata solo la posizione della città scelta, niente della tua casa."],
  ["Tout ce que fait Sally : lumières, prises, volets, chauffage programmé, routines, ambiances, suivi de l'énergie, alertes et sauvegarde. Sans cloud.",
    "Everything Sally does: lights, plugs, shutters, scheduled heating, routines, scenes, energy tracking, alerts and backup. No cloud.",
    "Alles, was Sally kann: Licht, Steckdosen, Rollläden, zeitgesteuerte Heizung, Routinen, Szenen, Energieübersicht, Alarme und Sicherung. Ohne Cloud.",
    "Todo lo que hace Sally: luces, enchufes, persianas, calefacción programada, rutinas, ambientes, seguimiento de la energía, alertas y copia de seguridad. Sin nube.",
    "Tutto quello che fa Sally: luci, prese, tapparelle, riscaldamento programmato, routine, scenari, monitoraggio dell'energia, avvisi e backup. Senza cloud."],
  ["La page d'une pièce dans Sally : l'image du salon et les tuiles de ses appareils.",
    "A room page in Sally: the living room picture and the tiles of its devices.",
    "Die Seite eines Raums in Sally: das Bild des Wohnzimmers und die Kacheln seiner Geräte.",
    "La página de una habitación en Sally: la imagen del salón y las casillas de sus aparatos.",
    "La pagina di una stanza in Sally: l'immagine del soggiorno e i riquadri dei suoi dispositivi."],

  // --- Compatibilité ---
  ["Compatibilité de Sally Home Connect : Zigbee, EnOcean, Windows et Raspberry Pi",
    "Sally Home Connect compatibility: Zigbee, EnOcean, Windows and Raspberry Pi",
    "Kompatibilität von Sally Home Connect: Zigbee, EnOcean, Windows und Raspberry Pi",
    "Compatibilidad de Sally Home Connect: Zigbee, EnOcean, Windows y Raspberry Pi",
    "Compatibilità di Sally Home Connect: Zigbee, EnOcean, Windows e Raspberry Pi"],
  ["Ce qu'il te faut", "What you need", "Was du brauchst", "Lo que necesitas", "Cosa ti serve"],
  ["Sally est vendue seule, sans matériel. Tu choisis tes appareils parmi deux grandes familles sans fil : Zigbee et EnOcean.",
    "Sally is sold on its own, with no hardware. You choose your devices from two major wireless families: Zigbee and EnOcean.",
    "Sally wird allein verkauft, ohne Hardware. Du wählst deine Geräte aus zwei großen Funkfamilien: Zigbee und EnOcean.",
    "Sally se vende sola, sin material. Eliges tus aparatos entre dos grandes familias inalámbricas: Zigbee y EnOcean.",
    "Sally è venduta da sola, senza hardware. Scegli i tuoi dispositivi tra due grandi famiglie wireless: Zigbee ed EnOcean."],
  ["Un ordinateur chez toi", "A computer at home", "Ein Computer bei dir", "Un ordenador en casa", "Un computer a casa"],
  ["Un PC sous Windows 10 ou 11 qui reste allumé. Une version pour Raspberry Pi est en préparation.",
    "A Windows 10 or 11 PC that stays on. A Raspberry Pi version is on its way.",
    "Ein PC mit Windows 10 oder 11, der eingeschaltet bleibt. Eine Version für Raspberry Pi ist in Vorbereitung.",
    "Un PC con Windows 10 u 11 que se queda encendido. Se está preparando una versión para Raspberry Pi.",
    "Un PC con Windows 10 o 11 che resta acceso. Una versione per Raspberry Pi è in preparazione."],
  ["Une clé USB Zigbee", "A Zigbee USB stick", "Ein Zigbee-USB-Stick", "Una llave USB Zigbee", "Una chiavetta USB Zigbee"],
  ["Elle parle aux ampoules, prises, modules et capteurs Zigbee. Sally est mise au point avec la clé Sonoff ZBDongle-P.",
    "It talks to Zigbee bulbs, plugs, modules and sensors. Sally is developed with the Sonoff ZBDongle-P stick.",
    "Er spricht mit Zigbee-Lampen, -Steckdosen, -Modulen und -Sensoren. Sally wird mit dem Stick Sonoff ZBDongle-P entwickelt.",
    "Habla con bombillas, enchufes, módulos y sensores Zigbee. Sally se desarrolla con la llave Sonoff ZBDongle-P.",
    "Parla con lampadine, prese, moduli e sensori Zigbee. Sally è sviluppata con la chiavetta Sonoff ZBDongle-P."],
  ["Une clé USB EnOcean", "An EnOcean USB stick", "Ein EnOcean-USB-Stick", "Una llave USB EnOcean", "Una chiavetta USB EnOcean"],
  ["Elle parle aux modules et interrupteurs EnOcean, souvent sans pile. Sally est mise au point avec la clé EnOcean USB 300.",
    "It talks to EnOcean modules and switches, often battery-free. Sally is developed with the EnOcean USB 300 stick.",
    "Er spricht mit EnOcean-Modulen und -Schaltern, oft ohne Batterie. Sally wird mit dem Stick EnOcean USB 300 entwickelt.",
    "Habla con módulos e interruptores EnOcean, a menudo sin pila. Sally se desarrolla con la llave EnOcean USB 300.",
    "Parla con moduli e interruttori EnOcean, spesso senza batteria. Sally è sviluppata con la chiavetta EnOcean USB 300."],
  ["Une seule des deux clés suffit. Sally reconnaît la clé toute seule quand tu la branches.",
    "Just one of the two sticks is enough. Sally recognises the stick by itself when you plug it in.",
    "Einer der beiden Sticks genügt. Sally erkennt den Stick von selbst, wenn du ihn einsteckst.",
    "Basta con una de las dos llaves. Sally reconoce la llave sola cuando la conectas.",
    "Basta una delle due chiavette. Sally riconosce la chiavetta da sola quando la colleghi."],
  ["Les appareils", "The devices", "Die Geräte", "Los aparatos", "I dispositivi"],
  ["Nous préférons être clairs : voici ce qui a été vérifié avec de vrais appareils, et ce qui est prêt dans Sally mais attend encore sa vérification.",
    "We prefer to be clear: here is what has been checked with real devices, and what is ready in Sally but still awaiting verification.",
    "Wir sind lieber ehrlich: Hier steht, was mit echten Geräten geprüft wurde und was in Sally bereit ist, aber noch auf die Prüfung wartet.",
    "Preferimos ser claros: esto es lo que se ha comprobado con aparatos reales, y lo que está listo en Sally pero aún espera su verificación.",
    "Preferiamo essere chiari: ecco cosa è stato verificato con dispositivi reali e cosa è pronto in Sally ma attende ancora la verifica."],
  ["Type d'appareil", "Device type", "Gerätetyp", "Tipo de aparato", "Tipo di dispositivo"],
  ["Ce que fait Sally", "What Sally does", "Was Sally macht", "Lo que hace Sally", "Cosa fa Sally"],
  ["État", "Status", "Stand", "Estado", "Stato"],
  ["Ampoules", "Bulbs", "Lampen", "Bombillas", "Lampadine"],
  ["Allumer, éteindre, régler l'intensité", "Switch on, switch off, dim", "Ein, aus, dimmen", "Encender, apagar, regular la intensidad", "Accendere, spegnere, regolare l'intensità"],
  ["Vérifié", "Verified", "Geprüft", "Comprobado", "Verificato"],
  ["Radiateurs à fil pilote", "Pilot-wire radiators", "Heizkörper mit Steuerleitung", "Radiadores con hilo piloto", "Termosifoni a filo pilota"],
  ["Confort, éco, hors gel, arrêt, puissance consommée (module NodOn)", "Comfort, eco, frost protection, off, power used (NodOn module)", "Komfort, Eco, Frostschutz, Aus, verbrauchte Leistung (NodOn-Modul)", "Confort, eco, antihielo, apagado, potencia consumida (módulo NodOn)", "Comfort, eco, antigelo, spento, potenza consumata (modulo NodOn)"],
  ["Prises", "Plugs", "Steckdosen", "Enchufes", "Prese"],
  ["Allumer, éteindre, mesurer la consommation", "Switch on, switch off, measure consumption", "Ein, aus, Verbrauch messen", "Encender, apagar, medir el consumo", "Accendere, spegnere, misurare il consumo"],
  ["En cours de validation", "Being validated", "In Prüfung", "En validación", "In fase di verifica"],
  ["Monter, descendre, arrêter, choisir une position", "Raise, lower, stop, choose a position", "Hoch, runter, Stopp, Position wählen", "Subir, bajar, parar, elegir una posición", "Alzare, abbassare, fermare, scegliere una posizione"],
  ["Thermostats", "Thermostats", "Thermostate", "Termostatos", "Termostati"],
  ["Lire la température, régler la consigne", "Read the temperature, set the target", "Temperatur ablesen, Sollwert einstellen", "Leer la temperatura, ajustar la consigna", "Leggere la temperatura, impostare il valore desiderato"],
  ["Température, mouvement, ouverture, fuite d'eau, fumée", "Temperature, motion, opening, water leak, smoke", "Temperatur, Bewegung, Öffnung, Wasserleck, Rauch", "Temperatura, movimiento, apertura, fuga de agua, humo", "Temperatura, movimento, apertura, perdita d'acqua, fumo"],
  ["Compteur Linky", "Linky meter", "Linky-Zähler", "Contador Linky", "Contatore Linky"],
  ["Suivre la consommation de toute la maison (module à brancher)", "Track the whole home's consumption (plug-in module)", "Den Verbrauch des ganzen Hauses verfolgen (Steckmodul)", "Seguir el consumo de toda la casa (módulo enchufable)", "Seguire il consumo di tutta la casa (modulo da collegare)"],
  ["Monter, descendre, arrêter (module NodOn)", "Raise, lower, stop (NodOn module)", "Hoch, runter, Stopp (NodOn-Modul)", "Subir, bajar, parar (módulo NodOn)", "Alzare, abbassare, fermare (modulo NodOn)"],
  ["Éclairage et prises", "Lighting and plugs", "Beleuchtung und Steckdosen", "Iluminación y enchufes", "Illuminazione e prese"],
  ["Allumer, éteindre", "Switch on, switch off", "Ein, aus", "Encender, apagar", "Accendere, spegnere"],
  ["Interrupteurs sans pile", "Battery-free switches", "Schalter ohne Batterie", "Interruptores sin pila", "Interruttori senza batteria"],
  ["Déclencher une routine par un appui", "Trigger a routine with a press", "Eine Routine per Tastendruck auslösen", "Activar una rutina con una pulsación", "Avviare una routine con una pressione"],
  ["Contacts de porte et de fenêtre", "Door and window contacts", "Tür- und Fensterkontakte", "Contactos de puerta y ventana", "Contatti per porte e finestre"],
  ["Savoir si c'est ouvert ou fermé", "Know whether it's open or closed", "Wissen, ob offen oder geschlossen", "Saber si está abierto o cerrado", "Sapere se è aperto o chiuso"],
  ["Tu as un appareil précis en tête ?", "Have a specific device in mind?", "Du hast ein bestimmtes Gerät im Kopf?", "¿Tienes un aparato concreto en mente?", "Hai in mente un dispositivo preciso?"],
  ["Écris-nous", "Write to us", "Schreib uns", "Escríbenos", "Scrivici"],
  [", on te dira où il en est.", " and we'll tell you where it stands.", ", wir sagen dir, wie weit es ist.", " y te diremos en qué punto está.", " e ti diremo a che punto è."],
  ["Le matériel qu'il faut pour Sally : un ordinateur, une clé USB Zigbee ou EnOcean, et les appareils déjà vérifiés ou en cours de validation.",
    "The hardware you need for Sally: a computer, a Zigbee or EnOcean USB stick, and the devices already verified or being validated.",
    "Die Hardware für Sally: ein Computer, ein Zigbee- oder EnOcean-USB-Stick und die bereits geprüften oder in Prüfung befindlichen Geräte.",
    "El material que necesita Sally: un ordenador, una llave USB Zigbee o EnOcean, y los aparatos ya comprobados o en validación.",
    "L'hardware che serve a Sally: un computer, una chiavetta USB Zigbee o EnOcean e i dispositivi già verificati o in fase di verifica."],

  // --- Obtenir Sally ---
  ["Essayer Sally Home Connect gratuitement : bêta Windows", "Try Sally Home Connect for free: Windows beta", "Sally Home Connect kostenlos testen: Windows-Beta", "Probar Sally Home Connect gratis: beta para Windows", "Prova Sally Home Connect gratis: beta per Windows"],
  ["La bêta de Sally pour Windows est disponible. Tu as 30 jours d'essai complet, sans compte et sans carte bancaire. Une démonstration est incluse pour tout découvrir, même sans matériel.",
    "The Sally beta for Windows is available. You get a full 30-day trial, no account and no credit card. A demo is included so you can explore everything, even without hardware.",
    "Die Sally-Beta für Windows ist verfügbar. Du hast 30 Tage voller Testzeitraum, ohne Konto und ohne Kreditkarte. Eine Demo ist dabei, um alles zu entdecken, auch ohne Hardware.",
    "La beta de Sally para Windows está disponible. Tienes 30 días de prueba completa, sin cuenta y sin tarjeta bancaria. Incluye una demostración para descubrirlo todo, incluso sin material.",
    "La beta di Sally per Windows è disponibile. Hai 30 giorni di prova completa, senza account e senza carta di credito. È inclusa una demo per scoprire tutto, anche senza hardware."],
  ["Télécharger la bêta Windows", "Download the Windows beta", "Windows-Beta herunterladen", "Descargar la beta para Windows", "Scarica la beta per Windows"],
  ["Windows 10 ou 11 (64 bits), environ 80 Mo. Le fichier est publié sur GitHub, où se trouvent aussi le guide d'installation et les nouveautés de chaque version.",
    "Windows 10 or 11 (64-bit), about 80 MB. The file is published on GitHub, where you'll also find the installation guide and what's new in each version.",
    "Windows 10 oder 11 (64 Bit), etwa 80 MB. Die Datei liegt auf GitHub, wo du auch die Installationsanleitung und die Neuerungen jeder Version findest.",
    "Windows 10 u 11 (64 bits), unos 80 MB. El archivo está publicado en GitHub, donde también encontrarás la guía de instalación y las novedades de cada versión.",
    "Windows 10 o 11 (64 bit), circa 80 MB. Il file è pubblicato su GitHub, dove trovi anche la guida all'installazione e le novità di ogni versione."],
  ["Choisis ta messagerie : un message déjà prêt s'ouvre, avec quelques questions sur ta maison et ton matériel. Complète-le et envoie-le, c'est tout. Rien n'est enregistré sur ce site.",
    "Choose your email: a ready-made message opens, with a few questions about your home and your hardware. Fill it in and send it, that's all. Nothing is stored on this site.",
    "Wähle dein E-Mail-Programm: Eine fertige Nachricht öffnet sich, mit ein paar Fragen zu deinem Zuhause und deiner Hardware. Ausfüllen, abschicken, fertig. Auf dieser Seite wird nichts gespeichert.",
    "Elige tu correo: se abre un mensaje ya preparado, con algunas preguntas sobre tu casa y tu material. Complétalo y envíalo, eso es todo. No se guarda nada en este sitio.",
    "Scegli la tua posta: si apre un messaggio già pronto, con qualche domanda sulla tua casa e sul tuo hardware. Completalo e invialo, tutto qui. Su questo sito non viene salvato nulla."],
  ["Écrire avec Gmail", "Write with Gmail", "Mit Gmail schreiben", "Escribir con Gmail", "Scrivi con Gmail"],
  ["Écrire avec Outlook.com", "Write with Outlook.com", "Mit Outlook.com schreiben", "Escribir con Outlook.com", "Scrivi con Outlook.com"],
  ["Avec ma messagerie", "With my email app", "Mit meinem E-Mail-Programm", "Con mi correo", "Con la mia posta"],
  ["Ou écris simplement à", "Or simply write to", "Oder schreib einfach an", "O escribe simplemente a", "Oppure scrivi semplicemente a"],
  ["Copier l'adresse", "Copy the address", "Adresse kopieren", "Copiar la dirección", "Copia l'indirizzo"],
  ["Installer Sally en trois étapes", "Install Sally in three steps", "Sally in drei Schritten installieren", "Instalar Sally en tres pasos", "Installare Sally in tre passaggi"],
  ["Rien d'autre à installer : tout ce dont Sally a besoin est dans le fichier.", "Nothing else to install: everything Sally needs is in the file.", "Sonst nichts zu installieren: Alles, was Sally braucht, steckt in der Datei.", "Nada más que instalar: todo lo que Sally necesita está en el archivo.", "Nient'altro da installare: tutto ciò che serve a Sally è nel file."],
  ["Lance l'installation", "Run the installer", "Starte die Installation", "Inicia la instalación", "Avvia l'installazione"],
  ["Double-clique sur le fichier téléchargé. Si Windows affiche « Windows a protégé votre ordinateur », choisis « Informations complémentaires » puis « Exécuter quand même » : la bêta n'est pas encore signée.",
    "Double-click the downloaded file. If Windows shows “Windows protected your PC”, choose “More info” then “Run anyway”: the beta is not signed yet.",
    "Doppelklicke auf die heruntergeladene Datei. Zeigt Windows „Der Computer wurde durch Windows geschützt“, wähle „Weitere Informationen“ und dann „Trotzdem ausführen“: Die Beta ist noch nicht signiert.",
    "Haz doble clic en el archivo descargado. Si Windows muestra «Windows protegió su PC», elige «Más información» y luego «Ejecutar de todas formas»: la beta aún no está firmada.",
    "Fai doppio clic sul file scaricato. Se Windows mostra «PC protetto da Windows», scegli «Ulteriori informazioni» e poi «Esegui comunque»: la beta non è ancora firmata."],
  ["Ouvre Sally", "Open Sally", "Öffne Sally", "Abre Sally", "Apri Sally"],
  ["L'icône du Bureau ouvre Sally dans ton navigateur. La première fois, il affiche un avertissement : c'est normal, Sally a son propre certificat. Choisis « Continuer ».",
    "The desktop icon opens Sally in your browser. The first time, it shows a warning: that's normal, Sally has its own certificate. Choose “Continue”.",
    "Das Desktop-Symbol öffnet Sally in deinem Browser. Beim ersten Mal zeigt er eine Warnung: Das ist normal, Sally hat ein eigenes Zertifikat. Wähle „Weiter“.",
    "El icono del escritorio abre Sally en tu navegador. La primera vez muestra un aviso: es normal, Sally tiene su propio certificado. Elige «Continuar».",
    "L'icona sul desktop apre Sally nel browser. La prima volta compare un avviso: è normale, Sally ha un proprio certificato. Scegli «Continua»."],
  ["Branche ta clé Zigbee ou EnOcean : Sally te guide, à la voix si tu veux. Sans matériel, ouvre « Sally Home Connect - Démonstration » dans le menu Démarrer.",
    "Plug in your Zigbee or EnOcean stick: Sally guides you, by voice if you like. Without hardware, open “Sally Home Connect - Démonstration” (the demo) from the Start menu.",
    "Steck deinen Zigbee- oder EnOcean-Stick ein: Sally führt dich, auf Wunsch per Sprache. Ohne Hardware öffnest du „Sally Home Connect - Démonstration“ (die Demo) im Startmenü.",
    "Conecta tu llave Zigbee o EnOcean: Sally te guía, con la voz si quieres. Sin material, abre «Sally Home Connect - Démonstration» (la demo) en el menú Inicio.",
    "Collega la tua chiavetta Zigbee o EnOcean: Sally ti guida, anche a voce se vuoi. Senza hardware, apri «Sally Home Connect - Démonstration» (la demo) dal menu Start."],
  ["Windows pour essayer, Raspberry Pi pour vivre avec", "Windows to try it, Raspberry Pi to live with it", "Windows zum Testen, Raspberry Pi für den Alltag", "Windows para probarla, Raspberry Pi para vivir con ella", "Windows per provarla, Raspberry Pi per viverci"],
  ["La bêta Windows sert à découvrir Sally. Pour l'adopter, la version finale tournera sur un Raspberry Pi : un petit boîtier silencieux qui reste allumé jour et nuit, sans écran ni clavier.",
    "The Windows beta is for discovering Sally. To adopt it, the final version will run on a Raspberry Pi: a small, silent box that stays on day and night, with no screen or keyboard.",
    "Die Windows-Beta dient zum Kennenlernen. Für den Alltag läuft die finale Version auf einem Raspberry Pi: ein kleines, leises Gerät, das Tag und Nacht läuft, ohne Bildschirm und Tastatur.",
    "La beta para Windows sirve para descubrir Sally. Para adoptarla, la versión final funcionará en una Raspberry Pi: una cajita silenciosa que se queda encendida día y noche, sin pantalla ni teclado.",
    "La beta per Windows serve a scoprire Sally. Per adottarla, la versione finale girerà su un Raspberry Pi: una piccola scatola silenziosa che resta accesa giorno e notte, senza schermo né tastiera."],
  ["Ensuite, une licence, pas un abonnement", "Then a licence, not a subscription", "Danach eine Lizenz, kein Abo", "Después, una licencia, no una suscripción", "Poi una licenza, non un abbonamento"],
  ["Après l'essai, Sally s'active avec une licence faite pour ton installation : tu paies une fois, sans abonnement. Son prix sera annoncé à la sortie.",
    "After the trial, Sally is activated with a licence made for your installation: you pay once, with no subscription. The price will be announced at launch.",
    "Nach dem Test wird Sally mit einer Lizenz für deine Installation aktiviert: Du zahlst einmal, ohne Abo. Der Preis wird zum Start bekannt gegeben.",
    "Después de la prueba, Sally se activa con una licencia hecha para tu instalación: pagas una vez, sin suscripción. Su precio se anunciará en el lanzamiento.",
    "Dopo la prova, Sally si attiva con una licenza fatta per la tua installazione: paghi una volta, senza abbonamento. Il prezzo sarà annunciato al lancio."],
  ["Ton avis fait avancer Sally", "Your feedback moves Sally forward", "Deine Meinung bringt Sally voran", "Tu opinión hace avanzar a Sally", "Il tuo parere fa crescere Sally"],
  ["Ce qui marche, ce qui bloque, ce qui te manque, le matériel que tu as : tout nous intéresse. Écris-nous, ou ouvre une demande dans l'onglet « Issues » de la page GitHub.",
    "What works, what gets in the way, what you're missing, the hardware you have: we want to hear it all. Write to us, or open a request in the “Issues” tab of the GitHub page.",
    "Was funktioniert, was hakt, was dir fehlt, welche Hardware du hast: Alles interessiert uns. Schreib uns oder eröffne eine Anfrage im Tab „Issues“ der GitHub-Seite.",
    "Lo que funciona, lo que falla, lo que echas en falta, el material que tienes: todo nos interesa. Escríbenos o abre una solicitud en la pestaña «Issues» de la página de GitHub.",
    "Cosa funziona, cosa si blocca, cosa ti manca, l'hardware che hai: ci interessa tutto. Scrivici o apri una richiesta nella scheda «Issues» della pagina GitHub."],
  ["Signaler un problème", "Report a problem", "Problem melden", "Informar de un problema", "Segnala un problema"],
  ["Télécharge la bêta de Sally pour Windows : 30 jours d'essai complet, sans compte, avec une démonstration pour tout découvrir sans matériel.",
    "Download the Sally beta for Windows: a full 30-day trial, no account, with a demo to explore everything without hardware.",
    "Lade die Sally-Beta für Windows herunter: 30 Tage voller Test, ohne Konto, mit einer Demo, um alles ohne Hardware zu entdecken.",
    "Descarga la beta de Sally para Windows: 30 días de prueba completa, sin cuenta, con una demostración para descubrirlo todo sin material.",
    "Scarica la beta di Sally per Windows: 30 giorni di prova completa, senza account, con una demo per scoprire tutto senza hardware."],

  // --- Contact ---
  ["Contacter Sally Home Connect", "Contact Sally Home Connect", "Sally Home Connect kontaktieren", "Contactar con Sally Home Connect", "Contatta Sally Home Connect"],
  ["Sally est faite par un développeur indépendant, près de Montpellier. Chaque message est lu, et tu reçois une réponse par e-mail.",
    "Sally is made by an independent developer near Montpellier, France. Every message is read, and you get a reply by email.",
    "Sally wird von einem unabhängigen Entwickler in der Nähe von Montpellier (Frankreich) gemacht. Jede Nachricht wird gelesen, und du bekommst eine Antwort per E-Mail.",
    "Sally la hace un desarrollador independiente cerca de Montpellier (Francia). Cada mensaje se lee y recibes una respuesta por correo.",
    "Sally è realizzata da uno sviluppatore indipendente vicino a Montpellier (Francia). Ogni messaggio viene letto e ricevi una risposta via email."],
  ["Par e-mail", "By email", "Per E-Mail", "Por correo", "Via email"],
  ["Pour une question sur un appareil, donne sa marque et sa référence : la réponse sera plus précise.",
    "For a question about a device, give its brand and model: the answer will be more precise.",
    "Bei einer Frage zu einem Gerät nenne Marke und Modell: Die Antwort wird genauer.",
    "Para una pregunta sobre un aparato, indica su marca y su referencia: la respuesta será más precisa.",
    "Per una domanda su un dispositivo, indica marca e modello: la risposta sarà più precisa."],
  ["La bêta Windows est disponible. Le bouton prépare un message avec quelques questions sur ton logement et ton matériel : complète-le et envoie-le. Ton adresse ne sert qu'à te répondre : elle n'est ni revendue ni ajoutée à une liste de publicité.",
    "The Windows beta is available. The button prepares a message with a few questions about your home and your hardware: fill it in and send it. Your address is only used to reply to you: it is never sold or added to an advertising list.",
    "Die Windows-Beta ist verfügbar. Der Knopf bereitet eine Nachricht mit ein paar Fragen zu deiner Wohnung und deiner Hardware vor: ausfüllen und abschicken. Deine Adresse dient nur der Antwort: Sie wird weder verkauft noch in eine Werbeliste aufgenommen.",
    "La beta para Windows está disponible. El botón prepara un mensaje con algunas preguntas sobre tu vivienda y tu material: complétalo y envíalo. Tu dirección solo sirve para responderte: ni se vende ni se añade a una lista de publicidad.",
    "La beta per Windows è disponibile. Il pulsante prepara un messaggio con qualche domanda sulla tua abitazione e sul tuo hardware: completalo e invialo. Il tuo indirizzo serve solo a risponderti: non viene né venduto né aggiunto a una lista pubblicitaria."],
  ["Ce site ne contient aucun formulaire : rien n'est enregistré ici. Les boutons ouvrent simplement ta messagerie ou la page de téléchargement.",
    "This site has no forms: nothing is stored here. The buttons simply open your email or the download page.",
    "Diese Seite enthält kein Formular: Hier wird nichts gespeichert. Die Knöpfe öffnen einfach dein E-Mail-Programm oder die Download-Seite.",
    "Este sitio no tiene ningún formulario: aquí no se guarda nada. Los botones simplemente abren tu correo o la página de descarga.",
    "Questo sito non contiene moduli: qui non viene salvato nulla. I pulsanti aprono semplicemente la tua posta o la pagina di download."],
  ["Une question sur Sally, un appareil à vérifier, ou l'envie d'être prévenu de la sortie : écris-nous.",
    "A question about Sally, a device to check, or want to hear about the launch: write to us.",
    "Eine Frage zu Sally, ein Gerät zum Prüfen oder Lust, beim Start benachrichtigt zu werden: Schreib uns.",
    "Una pregunta sobre Sally, un aparato que comprobar o ganas de enterarte del lanzamiento: escríbenos.",
    "Una domanda su Sally, un dispositivo da verificare o la voglia di sapere quando esce: scrivici."],

  // --- Mentions légales ---
  ["Mentions légales de Sally Home Connect", "Sally Home Connect legal notice", "Impressum von Sally Home Connect", "Aviso legal de Sally Home Connect", "Note legali di Sally Home Connect"],
  ["Éditeur du site", "Site publisher", "Herausgeber der Website", "Editor del sitio", "Editore del sito"],
  ["Éditeur et responsable de la publication : Thierry Puglisi, entrepreneur individuel (EI)",
    "Publisher and person responsible for publication: Thierry Puglisi, sole trader (entrepreneur individuel, EI)",
    "Herausgeber und Verantwortlicher: Thierry Puglisi, Einzelunternehmer (entrepreneur individuel, EI)",
    "Editor y responsable de la publicación: Thierry Puglisi, empresario individual (entrepreneur individuel, EI)",
    "Editore e responsabile della pubblicazione: Thierry Puglisi, imprenditore individuale (entrepreneur individuel, EI)"],
  ["Adresse : 2 rue François Mitterrand, B24, 34920 Le Crès, France",
    "Address: 2 rue François Mitterrand, B24, 34920 Le Crès, France",
    "Anschrift: 2 rue François Mitterrand, B24, 34920 Le Crès, Frankreich",
    "Dirección: 2 rue François Mitterrand, B24, 34920 Le Crès, Francia",
    "Indirizzo: 2 rue François Mitterrand, B24, 34920 Le Crès, Francia"],
  ["Statut : micro-entreprise ; numéro SIRET en cours d'attribution",
    "Status: French micro-enterprise; SIRET number being assigned",
    "Rechtsform: französisches Kleinunternehmen (micro-entreprise); SIRET-Nummer wird vergeben",
    "Estatuto: microempresa francesa (micro-entreprise); número SIRET en trámite de asignación",
    "Forma giuridica: microimpresa francese (micro-entreprise); numero SIRET in corso di assegnazione"],
  ["Contact :", "Contact:", "Kontakt:", "Contacto:", "Contatto:"],
  ["Hébergeur", "Hosting", "Hosting", "Alojamiento", "Hosting"],
  ["Ce site est hébergé par GitHub Pages, un service de GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, États-Unis.",
    "This site is hosted by GitHub Pages, a service of GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, United States.",
    "Diese Website wird von GitHub Pages gehostet, einem Dienst von GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, USA.",
    "Este sitio está alojado en GitHub Pages, un servicio de GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, Estados Unidos.",
    "Questo sito è ospitato da GitHub Pages, un servizio di GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, Stati Uniti."],
  ["Données personnelles", "Personal data", "Personenbezogene Daten", "Datos personales", "Dati personali"],
  ["Ce site ne dépose aucun cookie et n'utilise aucun outil de mesure d'audience.", "This site sets no cookies and uses no audience-measurement tools.", "Diese Website setzt keine Cookies und nutzt keine Reichweitenmessung.", "Este sitio no instala ninguna cookie ni usa herramientas de medición de audiencia.", "Questo sito non deposita cookie e non usa strumenti di misurazione del pubblico."],
  ["Il ne contient aucun formulaire : aucune donnée n'y est saisie ni enregistrée.", "It has no forms: no data is entered or stored on it.", "Sie enthält kein Formular: Hier werden keine Daten eingegeben oder gespeichert.", "No contiene ningún formulario: no se introduce ni se guarda ningún dato.", "Non contiene moduli: nessun dato viene inserito o salvato."],
  ["Comme tout hébergeur, GitHub enregistre des informations techniques de connexion (adresse IP, date, page demandée) pour assurer le fonctionnement et la sécurité du service.",
    "Like any host, GitHub records technical connection information (IP address, date, page requested) to ensure the service runs securely.",
    "Wie jeder Hoster speichert GitHub technische Verbindungsdaten (IP-Adresse, Datum, aufgerufene Seite), um Betrieb und Sicherheit des Dienstes zu gewährleisten.",
    "Como cualquier proveedor de alojamiento, GitHub registra datos técnicos de conexión (dirección IP, fecha, página solicitada) para garantizar el funcionamiento y la seguridad del servicio.",
    "Come ogni hosting, GitHub registra dati tecnici di connessione (indirizzo IP, data, pagina richiesta) per garantire il funzionamento e la sicurezza del servizio."],
  ["Si tu nous écris, ton adresse e-mail et ton message servent uniquement à te répondre. Tu peux demander leur suppression à tout moment, à l'adresse de contact ci-dessus.",
    "If you write to us, your email address and message are used only to reply to you. You can ask for them to be deleted at any time, at the contact address above.",
    "Wenn du uns schreibst, dienen deine E-Mail-Adresse und deine Nachricht nur der Antwort. Du kannst jederzeit über die obige Kontaktadresse ihre Löschung verlangen.",
    "Si nos escribes, tu dirección de correo y tu mensaje solo sirven para responderte. Puedes pedir que se borren en cualquier momento, en la dirección de contacto indicada arriba.",
    "Se ci scrivi, il tuo indirizzo email e il tuo messaggio servono solo a risponderti. Puoi chiederne la cancellazione in qualsiasi momento, all'indirizzo di contatto qui sopra."],
  ["Le logiciel Sally", "The Sally software", "Die Software Sally", "El programa Sally", "Il software Sally"],
  ["Le logiciel Sally Home Connect fonctionne chez son utilisateur. Les informations de la maison (appareils, habitudes, consommation) restent sur l'ordinateur où Sally est installée et ne sont pas transmises à l'éditeur.",
    "The Sally Home Connect software runs at the user's home. Information about the home (devices, habits, consumption) stays on the computer where Sally is installed and is not sent to the publisher.",
    "Die Software Sally Home Connect läuft beim Nutzer. Die Informationen über das Zuhause (Geräte, Gewohnheiten, Verbrauch) bleiben auf dem Computer, auf dem Sally installiert ist, und werden nicht an den Herausgeber übermittelt.",
    "El programa Sally Home Connect funciona en casa de su usuario. La información de la casa (aparatos, hábitos, consumo) se queda en el ordenador donde está instalada Sally y no se transmite al editor.",
    "Il software Sally Home Connect funziona a casa dell'utente. Le informazioni sulla casa (dispositivi, abitudini, consumi) restano sul computer dove è installata Sally e non vengono trasmesse all'editore."],
  ["Propriété intellectuelle", "Intellectual property", "Geistiges Eigentum", "Propiedad intelectual", "Proprietà intellettuale"],
  ["Les textes, les images et le logo de ce site appartiennent à l'éditeur. Les polices Manrope et Bricolage Grotesque sont utilisées sous licence SIL Open Font License. Zigbee et EnOcean sont des marques de leurs propriétaires respectifs, citées pour décrire la compatibilité.",
    "The texts, images and logo of this site belong to the publisher. The Manrope and Bricolage Grotesque fonts are used under the SIL Open Font License. Zigbee and EnOcean are trademarks of their respective owners, mentioned to describe compatibility.",
    "Texte, Bilder und Logo dieser Website gehören dem Herausgeber. Die Schriften Manrope und Bricolage Grotesque werden unter der SIL Open Font License verwendet. Zigbee und EnOcean sind Marken ihrer jeweiligen Inhaber und werden zur Beschreibung der Kompatibilität genannt.",
    "Los textos, las imágenes y el logotipo de este sitio pertenecen al editor. Las fuentes Manrope y Bricolage Grotesque se usan bajo la licencia SIL Open Font License. Zigbee y EnOcean son marcas de sus respectivos propietarios, citadas para describir la compatibilidad.",
    "I testi, le immagini e il logo di questo sito appartengono all'editore. I font Manrope e Bricolage Grotesque sono usati con licenza SIL Open Font License. Zigbee ed EnOcean sono marchi dei rispettivi proprietari, citati per descrivere la compatibilità."],
  ["Éditeur du site, hébergeur, données personnelles et propriété intellectuelle.", "Site publisher, hosting, personal data and intellectual property.", "Herausgeber, Hosting, personenbezogene Daten und geistiges Eigentum.", "Editor del sitio, alojamiento, datos personales y propiedad intelectual.", "Editore del sito, hosting, dati personali e proprietà intellettuale."],

  // --- Page introuvable ---
  ["Page introuvable | Sally Home Connect", "Page not found | Sally Home Connect", "Seite nicht gefunden | Sally Home Connect", "Página no encontrada | Sally Home Connect", "Pagina non trovata | Sally Home Connect"],
  ["Page introuvable", "Page not found", "Seite nicht gefunden", "Página no encontrada", "Pagina non trovata"],
  ["Cette page n'existe plus", "This page no longer exists", "Diese Seite gibt es nicht mehr", "Esta página ya no existe", "Questa pagina non esiste più"],
  ["Le site a été refait : certaines anciennes pages ont disparu. Tout ce qu'il faut savoir sur Sally est à portée de clic.",
    "The site has been rebuilt: some old pages have disappeared. Everything you need to know about Sally is just a click away.",
    "Die Website wurde neu gestaltet: Einige alte Seiten gibt es nicht mehr. Alles Wichtige über Sally ist nur einen Klick entfernt.",
    "El sitio se ha rehecho: algunas páginas antiguas han desaparecido. Todo lo que hay que saber sobre Sally está a un clic.",
    "Il sito è stato rifatto: alcune vecchie pagine sono sparite. Tutto quello che c'è da sapere su Sally è a portata di clic."],
  ["Revenir à l'accueil", "Back to home", "Zurück zur Startseite", "Volver al inicio", "Torna alla home"],
  ["Voir les fonctionnalités", "See the features", "Funktionen ansehen", "Ver las funciones", "Vedi le funzionalità"],
  ["Cette page n'existe pas ou a été déplacée.", "This page does not exist or has been moved.", "Diese Seite existiert nicht oder wurde verschoben.", "Esta página no existe o se ha movido.", "Questa pagina non esiste o è stata spostata."]
];
